[build]
  command = "nix-build"
  publish = "result/"

[build.environment]
  NIX_PATH = "nixpkgs=https://github.com/NixOS/nixpkgs/archive/21.11.tar.gz"

[[plugins]]
package = "netlify-plugin-nix-build"
  inputs = ["package.*", "shell.*"]