[build]
  # Cấu hình lệnh build của bạn. Đảm bảo rằng câu lệnh này tạo ra tất cả các tài sản cần thiết.
  command = "nix-build --dry-run ./nix/release.nix"

  # Thư mục gốc của dự án, đảm bảo đặt đúng đường dẫn tới thư mục gốc.
  base = "/"

# Cấu hình biến môi trường. Đặt các biến môi trường cần thiết cho dự án của bạn ở đây.
[context.production.environment]
  GEOCODE_API_KEY = "AIzaSyB-qm3rnTxXDi5xM0ATr0wEDBv0gMuI41U"
  
[context.branch-deploy.environment]
  GEOCODE_API_KEY = "AIzaSyB-qm3rnTxXDi5xM0ATr0wEDBv0gMuI41U"
  
[context.deploy-preview.environment]
  GEOCODE_API_KEY = "AIzaSyB-qm3rnTxXDi5xM0ATr0wEDBv0gMuI41U"

# Cấu hình phiên bản Node.js
[build.environment]
  NODE_VERSION = "14"

# Cấu hình phiên bản Ruby (nếu bạn cần)
[runtime]
  name = "ruby"
  version = "2.7"

# Cấu hình phiên bản Python (nếu bạn cần)
[runtime]
  name = "python"
  version = "3.8"
